In [19]:
import numpy as np

In [18]:
a = np.array([[1],[2],[3]])
b = np.array([1,2,3])
c = np.array([4,5,6])

array([-3, -3, -3])

In [20]:
np.sum(a,1) - c

array([-3, -3, -3])

In [21]:
a - c

array([[-3, -4, -5],
       [-2, -3, -4],
       [-1, -2, -3]])

In [14]:
b - c

array([-3, -3, -3])

In [23]:
print(a.shape, b.shape, c.shape)

(3, 1) (3,) (3,)
