In [1]:
import numpy
numpy.__version__

'1.13.3'

In [1]:
import numpy as np

In [2]:
np.

SyntaxError: invalid syntax (<ipython-input-2-a58a88215da2>, line 1)

In [3]:
np?

관련 설명을 참조하여 보려면 http://www.numpy.org

파이선 정수는 정수 이상이다.

파이선 정수는 PyOject_HEAD(참조 횟수, 타입코드, 전에 언급된 다른 정보등 포함)과 숫자로 이루어짐
==> 단순 숫자 아상임

자유롭게 동적으로 코드를 작성할 수  있는 반면 비용이 존재 한다

파이선 리스트는 리스트 이상이다.

파이선 리스트는 각 항목에 타입 정보와 참조 횟수, 기타 정보가 들어가서 유연한 활용 가능함

자유롭게 동적으로 코드를 작성할 수  있는 반면 비용이 존재 한다

In [19]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [22]:
type(L2[0])

str

파이선의 동적 타이핑 덕분에 다른 데이터 타입의 요소를 담는 리스트도 만들 수 있음

In [23]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

반면 Numpy는 고정 타입이며 유연성은 부족하지만 데이터를 저장하고 가공하기에는 훨씬 더 효율적이다

내장 array 모듈도 단일 타입의 조밀한 배열을 만드는데 사용할 수 있다

In [1]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

그러나 훨씬 더 유용한 것은 Numpy의 ndarray 객체이다. 효율적인 연산을 추가한다.

Numpy의 배열 만들기
np.array를 활용하여 배열을 만들 수 있다
Numpy의 배열은 모두 같은 요소 타입 이어야 한다 ==> 타입이 일치하지 않으면 상위 타입으로
리스트를 중첩하면 다차원이 가능하다

In [2]:
import numpy as np

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float')

array([ 1.,  2.,  3.,  4.])

In [10]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

처음부터 배열 만들기

In [11]:
# 0으로 채운 길이 10의 정수 배열 만들기

np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
# 1로 채운 3x5 부동 소수점으로 배열 만들기

np.ones((3,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
np.ones([3,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [14]:
np.ones((3,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
#3.14 로 만든 3x5 배열 만들기

np.full((3,5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [19]:
# 선형 수열로 채운 배열 만들기
# 0에서 시작해 2씩 더해 20까지 채움
# (내장 함수인 range()와 유사함)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# 0과 1 사이에 일정한 간격을 가진 다섯개의 값으로 채운 배열 np.linspace(start, stop, num=50, endpoint=True, 
retstep=False, dtype=None)

np.linspace(0,1,5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [21]:
# 균등하게 분포한 3x3 배열 만들기 random_sample(size=None)
# 0과 1의 난수로 채움

np.random.random((3,3))

array([[ 0.92341386,  0.95699166,  0.3567777 ],
       [ 0.33986546,  0.41146451,  0.20065569],
       [ 0.69751727,  0.63124157,  0.22289916]])

In [22]:
# 정규분포 (평균=0 표준편차=1)의 난수로 채운 3x3 배열 만들기 normal(loc=0.0, scale=1.0, size=None)

np.random.normal(0, 1, (3,3))

array([[ 1.12191554, -0.25518567,  0.55829507],
       [-0.17982415,  0.57385811, -0.81513881],
       [-0.19112581, -0.5145558 , -0.52813322]])

In [12]:
# 0에서 10사이의 임의의 정수로 채운 3x3 배열 만들기 randint(low, high=None, size=None, dtype='l')

np.random.randint(0, 10, [3,3])

array([[5, 8, 9],
       [0, 4, 2],
       [6, 5, 5]])

In [13]:
np.random.randint(0, 10, (3,3))

array([[5, 0, 3],
       [4, 9, 1],
       [6, 5, 9]])

In [24]:
# 3x3 단위 행렬 만들기 np.eye(N, M=None, k=0, dtype=<class 'float'>)

np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
# 세 개의 정수를 가지는 uninitialized or arbitrary 배열 만들기 empty(shape, dtype=float, order='C')
# 값은 해당 메모리 위치에 이미 존재하고 있는 값으로 채움

np.empty(3)

array([ 1.,  1.,  1.])

In [6]:
np.empty((2,2))

array([[  1.38233094e-311,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000]])

In [7]:
np.empty((2,2), dtype=int)

array([[1483866409, 1912602624],
       [         9,       2418]])

In [9]:
np.empty([2,2])

array([[  1.38233095e-311,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000]])

In [10]:
np.empty([2,2], dtype=int)

array([[ 690436402,  537528925],
       [ 538976288, 1864376352]])