배열 속성지정 = 배열의 크기, 모양, 메모리 소비량, 데이터 타입을 결정함

배열 인덱싱 = 개별 배열의 요소값을 가져오고 설정한다

배열 슬라이싱 = 큰 배열내에 있는 작은 하위 배열을 가져오고 설정한다

배열 재구조화 = 해당 배열의 형상을 변경한다

배열 결합 및 분할 = 여러 배열을 하나로 결합하고 하나의 배열을 여러개로 분할 한다

배열 속성 지정

In [1]:
import numpy as np
np.random.seed(0) # 재현 가능한 시드값 seed(seed=None) It can be called again to re-seed the generator

x1 = np.random.randint(10, size=6) # 1차원 배열 randint(low, high=None, size=None, dtype='l')
x2 = np.random.randint(10, size=(3,4)) # 2차원 배열
x3 = np.random.randint(10, size=(3,4,5)) # 3차원 배열

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

ndim = 차원의 갯수, shape = 각 차원의 크기, size = 전체 배열 크기

In [6]:
print('x3 ndim:', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size:', x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [8]:
x3.dtype

dtype('int32')

In [9]:
x3.itemsize # bytes

4

In [10]:
x3.nbytes # itemseze x size, bytes

240

배열 인덱싱 = 단일 요소에 접근하기

In [11]:
x1

array([5, 0, 3, 3, 7, 9])

In [12]:
x1[0]

5

In [13]:
x1[4]

7

In [14]:
x1[-1]

9

다차원 배열에서는 콤마로 구분된 인덱스 튜플을 이용해 접급

In [15]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [16]:
x2[0,0]

3

In [17]:
x2[2,0]

1

In [18]:
x2[2,-1]

7

인덱스 값 수정하기

In [20]:
x2[0,0] = 12
x2

array([[12, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

파이선과는 달리 Numpy는 고정 타입을 가진다 따라서 정수 배열에 부동 소숫점을 입력하려 하면
부동 소숫점은 잘려 나간다

In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [22]:
x1[0] = 3.141592
x1

array([3, 0, 3, 3, 7, 9])

배열 슬라이싱 = 하위 배열에 접근하기

x[start:stop:step]

하나라도 지정 안되면 디폴트는 start=0, stop=size of dimension, step=1

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x[:5]

array([0, 1, 2, 3, 4])

In [25]:
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

array([4, 5, 6])

In [27]:
x[::2] # 처음부터 하나걸러 하나씩

array([0, 2, 4, 6, 8])

In [28]:
x[1::2] # 인덱스 1부터 하나 걸러 하나씩

array([1, 3, 5, 7, 9])

step의 값이 음수 일때 주의 요망 끄에서 부터 시작하라는 의미이며
즉 start와 stop의기본값이 바뀌며 배열을 거꾸로 만드는 편한 방법임

In [29]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]

array([5, 3, 1])

다차원 하위 배열

In [31]:
x2

array([[12, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
x2[:2, :3] # 두개의 행, 세개의 열

array([[12, 12,  2],
       [ 7,  6,  8]])

In [36]:
x2[:3, ::2] # 모든 행, 한열 건너 하나씩

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [37]:
x2[:, ::2] # 모든 행, 한열 건너 하나씩

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

하위 배열 역 변환

In [38]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2, 12, 12]])

In [39]:
x2[:, 0] # 첫번째 열

array([12,  7,  1])

In [40]:
x2[0, :] # 첫번째 행

array([12, 12,  2,  4])

In [41]:
x2[0] # 행의 경우는 간략하게 표현 가능함

array([12, 12,  2,  4])

NUMPY에서는 배열을 슬라이싱하고 하위 배열로 지정하여 작업을 하여 변화가 생기면 
상위배열도 자동적으로 변화 한다.

사본이 아니라 원본 뷰로 나타남

In [42]:
print(x2)

[[12 12  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [43]:
x2_sub = x2[:2, :2]
x2_sub

array([[12, 12],
       [ 7,  6]])

In [44]:
x2_sub[0,0] = 99
x2_sub

array([[99, 12],
       [ 7,  6]])

In [45]:
x2

array([[99, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

배열의 사본 만들기

하위배열을 변수 선언을 할때 .copy() 메서드를 활용한다

In [46]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[99, 12],
       [ 7,  6]])

In [48]:
x2_sub_copy[0,0] = 42
x2_sub_copy

array([[42, 12],
       [ 7,  6]])

In [49]:
x2 # 원본은 99로 그대로 있다

array([[99, 12,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

배열 재구조화 reshape 함수 / newaxis 키워드

In [1]:
import numpy as np
grid = np.arange(1,10).reshape((3,3)) # 초기 배열 구조와 변경된 배열의 구조가 일치 할 수 있어야 한다
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1차원 배열을 2차원 배열로 전환

In [5]:
x = np.array([1,2,3]) # reshape 를 이용하여 행벡터 만들기
x.reshape((1,3))

array([[1, 2, 3]])

In [6]:
x[np.newaxis, :] # newaxis를 이용한 행벡터

array([[1, 2, 3]])

In [7]:
x.reshape((3,1)) # reshape 를 이용하여 열벡터 만들기

array([[1],
       [2],
       [3]])

In [8]:
x[:, np.newaxis] # newaxis를 이용한 열벡터

array([[1],
       [2],
       [3]])

배열의 연결 및 분할

여러 배열을 하나로 결합 하거나 그 반대로 하나의 배열을 여러개의 배열로 분할 하는 것

배열 연결 

np.concatenate(차원 유지) / np.vstack(차원 유지) / np.hstack(차원 유지) / np.dstack (3차원 축을 따라 배열을 추가)

Docstring:
concatenate((a1, a2, ...), axis=0)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  Default is 0.

Returns
-------
res : ndarray
    The concatenated array.

See Also
--------
ma.concatenate : Concatenate function that preserves input masks.
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.
split : Split array into a list of multiple sub-arrays of equal size.
hsplit : Split array into multiple sub-arrays horizontally (column wise)
vsplit : Split array into multiple sub-arrays vertically (row wise)
dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).
stack : Stack a sequence of arrays along a new axis.
hstack : Stack arrays in sequence horizontally (column wise)
vstack : Stack arrays in sequence vertically (row wise)
dstack : Stack arrays in sequence depth wise (along third dimension)

Notes
-----
When one or more of the arrays to be concatenated is a MaskedArray,
this function will return a MaskedArray object instead of an ndarray,
but the input masks are *not* preserved. In cases where a MaskedArray
is expected as input, use the ma.concatenate function from the masked
array module instead.

Examples
--------
>>> a = np.array([[1, 2], [3, 4]])
>>> b = np.array([[5, 6]])
>>> np.concatenate((a, b), axis=0)
array([[1, 2],
       [3, 4],
       [5, 6]])
>>> np.concatenate((a, b.T), axis=1)
array([[1, 2, 5],
       [3, 4, 6]])

This function will not preserve masking of MaskedArray inputs.

>>> a = np.ma.arange(3)
>>> a[1] = np.ma.masked
>>> b = np.arange(2, 5)
>>> a
masked_array(data = [0 -- 2],
             mask = [False  True False],
       fill_value = 999999)
>>> b
array([2, 3, 4])
>>> np.concatenate([a, b])
masked_array(data = [0 1 2 2 3 4],
             mask = False,
       fill_value = 999999)
>>> np.ma.concatenate([a, b])
masked_array(data = [0 -- 2 2 3 4],
             mask = [False  True False False False False],
       fill_value = 999999)
Type:      builtin_function_or_method

In [5]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [6]:
z = [99, 99, 99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [7]:
grid = np.array([[1,2,3],
               [4,5,6]])

# 첫번쨰 dimension을 추가함 (예) axis=0, 2X 3와 2x3의 concatenation ==> 4x3로 확장 연결됨

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
# 두번째 dimension을 추가함 (예) axis=1, 2X 3와 2x3의 concatenation ==> 2x6로 확장 연결됨

np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

혼합된 차원의 배열로 작업할때는 np.vstack(vertical stack)과 np.hstack(horizontal stack)을 사용함 

In [9]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
               [6,5,4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [10]:
np.hstack([x, grid]) # 주의!!!

ValueError: all the input arrays must have same number of dimensions

In [12]:
y = np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [15]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.dstack((a,b))

array([[[1, 2],
        [2, 3],
        [3, 4]]])

Signature: np.dstack(tup)
Docstring:
Stack arrays in sequence depth wise (along third axis).

Takes a sequence of arrays and stack them along the third axis
to make a single array. Rebuilds arrays divided by `dsplit`.
This is a simple way to stack 2D arrays (images) into a single
3D array for processing.

This function continues to be supported for backward compatibility, but
you should prefer ``np.concatenate`` or ``np.stack``. The ``np.stack``
function was added in NumPy 1.10.

Parameters
----------
tup : sequence of arrays
    Arrays to stack. All of them must have the same shape along all
    but the third axis.

Returns
-------
stacked : ndarray
    The array formed by stacking the given arrays.

See Also
--------
stack : Join a sequence of arrays along a new axis.
vstack : Stack along first axis.
hstack : Stack along second axis.
concatenate : Join a sequence of arrays along an existing axis.
dsplit : Split array along third axis.

Notes
-----
Equivalent to ``np.concatenate(tup, axis=2)`` if `tup` contains arrays that
are at least 3-dimensional.

Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.dstack((a,b))
array([[[1, 2],
        [2, 3],
        [3, 4]]])

>>> a = np.array([[1],[2],[3]])
>>> b = np.array([[2],[3],[4]])
>>> np.dstack((a,b))
array([[[1, 2]],
       [[2, 3]],
       [[3, 4]]])
File:      c:\users\jsong\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Type:      function

배열 분할 하기

np.split(차원 유지) / np.vsplit(차원 유지) / np.hsplit(차원 유지) / np.dsplit(3차원 축을 따라 배열을 추가)


Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays.

Raises
------
ValueError
    If `indices_or_sections` is given as an integer, but
    a split does not result in equal division.

See Also
--------
array_split : Split an array into multiple sub-arrays of equal or
              near-equal size.  Does not raise an exception if
              an equal division cannot be made.
hsplit : Split array into multiple sub-arrays horizontally (column-wise).
vsplit : Split array into multiple sub-arrays vertically (row wise).
dsplit : Split array into multiple sub-arrays along the 3rd axis (depth).
concatenate : Join a sequence of arrays along an existing axis.
stack : Join a sequence of arrays along a new axis.
hstack : Stack arrays in sequence horizontally (column wise).
vstack : Stack arrays in sequence vertically (row wise).
dstack : Stack arrays in sequence depth wise (along third dimension).

Examples
--------
>>> x = np.arange(9.0)
>>> np.split(x, 3)
[array([ 0.,  1.,  2.]), array([ 3.,  4.,  5.]), array([ 6.,  7.,  8.])]

>>> x = np.arange(8.0)
>>> np.split(x, [3, 5, 6, 10])
[array([ 0.,  1.,  2.]),
 array([ 3.,  4.]),
 array([ 5.]),
 array([ 6.,  7.]),
 array([], dtype=float64)]
File:      c:\users\jsong\anaconda3\lib\site-packages\numpy\lib\shape_base.py
Type:      function

In [16]:
x = [1,2,3,99,99,3,2,1]

x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [17]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
upper, lower = np.vsplit(grid, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
left, right = np.hsplit(grid, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
np.dsplit() # 세번쨰 domension 에 따라 분열할 것